sudo: false
language: rust
rust:
  - stable
  - beta
  - nightly

addons:
  apt:
    sources:
    - llvm-toolchain-trusty-3.9
    packages:
    - libxml2-dev
    - clang-3.9

branches:
  only:
  - master

cache: cargo

script:
  - clang -v

  # Build
  - cargo build --verbose

  # Test
  - cargo test --verbose
