sudo: false
language: rust
rust:
  - stable
  - beta
  - nightly

addons:
  apt:
    packages:
    - libxml2-dev
    - libclang-dev

branches:
  only:
  - master

cache: cargo

script:
  - clang -v

  # Build
  - cargo build --verbose

  # Test
  - cargo test --verbose
